language: python
sudo: required

python:
  - "3.5"

install:
  - sudo apt-get install python3-pip
  - sudo pip3 install flake8

script:
  - python3 -m flake8

# notifications:
#  flowdock:
#    secure:
