language: python
sudo: required

python:
  - "3.5"

install:
  - pip install flake8

script:
  - flake8

notifications:
  flowdock:
    - secure: "oWNWWNY03yBN2KdTP84dnhx3h7E3NGsHXOlvizxB9Yc533ymrAR3+Zpn4UP3vJDiX5qz0TZtxI7RYEZDRK8vYP2zOrR4D/eRNx1vhu4bkLkyDGh0j4uVk28qWeZXtrH/qhlHChw4klkxkjvdQIhAg9gsswNxWlXIb4EdzatJysxeymGNXtoOLQ5qJCInkWqPxbudpD7QqNIi+4ea6FEKmr+MW0hBCWfjKn8Ip1YDdDHK+R+EGvyxU9CWi1kNYFcXN2WwKGZI1jjaTnCWWaFIthttdAsKFONd3/kYfRA2Xhlr9mEixaFsBZsKNtrpq+SNlU9jHhJ6Pr3YA/2IifqDFks0IWbnyA7Kbt8HS/Cvvb3MzB4lxaJjX6NcokYib7c6YKt3bfp2iJ5htjDm9j57e+ivSyAjcMNnPoJszTXgNLO1N3dDIgJH0Q5GqAFefZ4IHS7L7vWma0DSLKi0zsK06mi5rF5l000k6yCOSwhZRP2PIovas32PF6maDcTj9RSMWWbF2AuuoOkIsgxzXlbh4ETILDK4SCROuDJTxkuB5amKvi+lOJywtic5RVLda66pz7KOgRAPcLJPbs78Ft3GHewN30ctBYKEAvzw5JJHPaPovng7K706Qzg7SaUx0+r52bMYXLO4rDW8tFJMgUmm7pZfAEkrqTCtsKVcPw9u6XY="
    - secure: "UH2AHF1pEAw0oYWGH10ZjuFrHwP3qIYr8cCpEF3eX6uVxT0NoyddFL4WKLLq0wfzH6P/k68S40bTNhvD26pOHzwxVza39IlWhsLVW2RdIdzP67TltRMTnUDi7rFruTvSP+H/3yiuQuMtwr+844veu6PGAl/mGD0fWEP7TA4M+Us9P05oFbvd7Q4eWbkQSLKwn+xDcyKze8ygudnWo2BCKdg1yRnZqAt6IkB8W1opVypBHX9Uv1ESJfUxUxztIl+LuSgcWRRm0W3QeoadwcOJ/A6x7OhGIdheKYUDXLYGksj7s6kP7hXh+WU+470DTlJrhlTkuQfIK96ES6qBXiAQfH29jUOgTtzfPlkdkUtWoFOKcWzGjw+8tQkuhhOY9TxKxlBaZ6XFVY+rPHqX+Ezf9aTOi34wTTDVeciPh4pwt+QdpbELQOUhtaQSTa013tN/ANMojM1KZmRsK3kRYHlaogFzofwGQxopr+Vb1u+kAlgH85qFoErqvs48LrSc5djGASL8c1E+ykbk/6+CqaKHTnTnDbYiEnB3D7ClGniCVcU8XAOayHR6nyrw4ukIQDYOWo2HXZgPX7k+2brCUKacKkDHP34sJZW8SvB1LtjO6hN0YePsIzid9V62L1R87bqGzxNGi+Nxam4OExz7qMESoB+a84YJDkPVqcQyxrYbOg0="
