language: python
sudo: required

python:
  - "3.5"

install:
  - sudo apt-get install python3-setuptools
  - sudo easy_install3 pip
  - pip --version
  - sudo pip install flake8

script:
  - python3 -m flake8

# notifications:
#  flowdock:
#    secure:
